# Generated by Django 6.1.1 on 2026-09-22 07:56

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[("income", "Income"), ("expense", "Expense")],
                        default="expense",
                        help_text="Whether this is an income or expense",
                        max_length=7,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Positive numeric amount (e.g. 25.50)",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(
                                Decimal("0.01"),
                                message="Amount must be greater than zero.",
                            )
                        ],
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Salary", "Salary"),
                            ("Food", "Food"),
                            ("Travel", "Travel"),
                            ("Shopping", "Shopping"),
                            ("Bills", "Bills"),
                            ("Education", "Education"),
                            ("Health", "Health"),
                            ("Entertainment", "Entertainment"),
                            ("Other", "Other"),
                        ],
                        default="Other",
                        help_text="Transaction category",
                        max_length=30,
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        default=django.utils.timezone.now,
                        help_text="Date when the transaction occurred",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="Optional brief description or note",
                        max_length=255,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Record creation timestamp"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The user who owns this transaction",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Transaction",
                "verbose_name_plural": "Transactions",
                "ordering": ["-date", "-created_at"],
            },
        ),
    ]
